### ISSUE TITLE
New Business Goal is placed.

### ISSUE THREAD

**Issue by jose598** [Jfede98/ISII-WORKSHOPS-JUEGOS_DE_KIOSKOS#1] opened 2022-01-14 00:58 UTC
Dear support team, we are satisfied about your hard work during this last year. On this new year we want to be bigger and better. In the meeting with the Accounting Department and Business Intelligent Group, we proposed some changes with the intention of improving our service and getting more customers. The new business rule establishes: If the customer is married and has more than 30 years old but younger than 60, then $50 must be decreased to the base premium for each one, however if the customer is single, woman and older than 60 years old , she will receive a discount for around $50.

You need to know that all rules should be maintained how it was coming. Our requirement should be added to the existing one and the result should be calculated with all rules applied.

**Comment by Jfede98** [comment] 2022-01-20 23:43
Hello! We have checked the code and find that the current version needs updates in order to apply the new business rules.
![cd566266-c0d8-4c0a-b432-21ba2f13c703](https://user-images.githubusercontent.com/66968793/150439629-1e62d39c-23bd-4cc0-9f65-2a71e6fb9ac7.jpg)
After the issue reproduction, we get a premium value of $300 instead of the expected $250. Issue verification completed. ✅

**Comment by Jfede98** [comment] 2022-01-20 23:46
Issue categorization completed.✅

**Comment by Jfede98** [comment] 2022-01-20 23:49
We will proceed to process the request, @gdmora will be the assigned analyst and will develop the solution, and @Jfede98 will perform the tests.

**Comment by jose598** [comment] 2022-01-21 00:33
Thank you

**Comment by gdmora** [comment] 2022-01-21 02:54
Hello @jose598 , please review the analysis performed on your feature request.

[Impact Analysis.pdf](https://github.com/Jfede98/ISII-WORKSHOPS-JUEGOS_DE_KIOSKOS/files/7909922/Impact.Analysis.pdf)

Additionally, in your description :

> If the customer is married and has more than 30 years old but younger than 60, then $50 must be decreased to the base premium for each one ...

It is not clear what do you mean by 'each one'.  Is the following interpretation correct?

- Subtract $50 if the customer is married.
- Subtract $50 if the customer has more than 30 years old but is younger than 60.
- Subtract $100 if the customer is married AND has more than 30 years old but is younger than 60.

**Comment by jose598** [comment] 2022-01-21 21:45
Everything is OK @gdmora.
According to what are you describing, the third one is the correct. 
Please start working on the issue.

**Comment by gdmora** [comment] 2022-01-21 22:02
The solution has been built.

https://github.com/Jfede98/ISII-WORKSHOPS-JUEGOS_DE_KIOSKOS/blob/0aa049ec41c346bb43d9856048b7efa9ca15a387/ec.edu.espol.workshops/lib/src/main/java/ec/edu/espol/workshops/CarInsurance.java#L80-L119

**Comment by jose598** [comment] 2022-01-21 22:11
@gdmora I have observation: 
I said: Subtract $100 if the customer is married AND has more than 30 years old but is younger than 60 but you're not doing that, also no consider customer with 30 years old, it's more than 30, no included. Sideway, I watched that you decrease if the customer is married, that is a new rules? And also why your considering a customer married status false to the customer over 60 years old for giving the discount, this one is about the second rules mentioned on the issue.

**Comment by gdmora** [comment] 2022-01-21 22:17
@jose598 I misunderstood what you said before, apologies. I'll make the necessary corrections on the code.

**Comment by jose598** [comment] 2022-01-21 22:20
@gdmora no worry. I got it.

**Comment by gdmora** [comment] 2022-01-21 22:23
@jose598 Regarding the second rule, it states :

>  if the customer is single, woman and older than 60 years old , she will receive a discount for around $50.

that's the reason the married status is false for the rule to apply.

> And also why your considering a customer married status false to the customer over 60 years old for giving the discount, this one is about the second rules mentioned on the issue.

False married status is equivalence to single.

**Comment by jose598** [comment] 2022-01-21 22:29
Ok, thank you. @gdmora 
I got it.

**Comment by gdmora** [comment] 2022-01-21 22:37
Corrections done!

https://github.com/Jfede98/ISII-WORKSHOPS-JUEGOS_DE_KIOSKOS/blob/758a3d0ab20911c46005188cc02e39897359713b/ec.edu.espol.workshops/lib/src/main/java/ec/edu/espol/workshops/CarInsurance.java#L80-L114

**Comment by jose598** [comment] 2022-01-21 22:52
Thank you! Please continue with the test plan @gdmora

**Comment by Jfede98** [comment] 2022-01-21 22:57
Test plan completed
[Test Plan.docx](https://github.com/Jfede98/ISII-WORKSHOPS-JUEGOS_DE_KIOSKOS/files/7917037/Test.Plan.docx)

**Comment by jose598** [comment] 2022-01-21 23:06
OK, Thank you for solving this issue. 

You can close the issue.

**Comment by Jfede98** [comment] 2022-01-21 23:16
@jose598 Can you review the acceptance plan
[Acceptance testing.docx](https://github.com/Jfede98/ISII-WORKSHOPS-JUEGOS_DE_KIOSKOS/files/7917091/Acceptance.testing.docx)
?

**Comment by jose598** [comment] 2022-01-21 23:18
Yes, everything is OK. 

Thank you

**Comment by Jfede98** [comment] 2022-01-21 23:22
@jose598 Can you execute the acceptance plan to verify if they pass?

**Comment by jose598** [comment] 2022-01-21 23:44
Yes, I did. 
@Jfede98  
Everything has been passed.

**Comment by Jfede98** [comment] 2022-01-21 23:48
Do you accept our solution?

**Comment by jose598** [comment] 2022-01-21 23:50
Yes. 
Thank you for your support

**Comment by Jfede98** [comment] 2022-01-21 23:54
@jose598 The solution has been completed and @gdmora will realease the new software version.

**Comment by jose598** [comment] 2022-01-22 00:05
Ok, @Jfede98

**Comment by gdmora** [comment] 2022-01-22 00:13
@jose598 

Version 1.0 of the software has been released.

The user manual is here.


[User manual.pdf](https://github.com/Jfede98/ISII-WORKSHOPS-JUEGOS_DE_KIOSKOS/files/7917228/User.manual.pdf)

**Comment by jose598** [comment] 2022-01-22 00:48
Thank you @gdmora 
I will try to use it.

**Comment by Jfede98** [comment] 2022-01-22 00:51
@jose598 Could you use the software without any trouble? Are you satisfied with the solution?

**Comment by jose598** [comment] 2022-01-22 00:52
Yes I'm glad of using this new version.
Thank you @Jfede98

**Comment by Jfede98** [comment] 2022-01-22 00:58
Closing the ticket

**Closed as completed** 2022-01-22 00:59 UTC
Labels: Issue reproduction, Issue categorization, Issue assignment, Impact analysis, Solve the issue, Test the solution, Acceptance testing, Completeness verification, Enactment of the solution, Follow up, High priority
